gtm_barebones.settings:
  type: config_object
  label: 'GTM Barebones Settings'
  mapping:
    container_id:
      type: string
      label: 'GTM Container ID'
    environment_id:
      type: string
      label: 'Environment ID'
    environment_token:
      type: string
      label: 'Environment token'
